CREATE SEQUENCE SEQ_PAUTA START WITH 1 INCREMENT BY 1;

CREATE TABLE PAUTA (
                       ID        NUMBER(19)    NOT NULL,
                       TITULO    VARCHAR2(200) NOT NULL,
                       DESCRICAO VARCHAR2(1000),
                       CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
                       CONSTRAINT PK_PAUTA PRIMARY KEY (ID)
);

CREATE INDEX IDX_PAUTA_TITULO ON PAUTA (TITULO);
