CREATE SEQUENCE SEQ_SESSAO START WITH 1 INCREMENT BY 1;

CREATE TABLE SESSAO_VOTACAO (
                                ID        NUMBER(19) NOT NULL,
                                PAUTA_ID  NUMBER(19) NOT NULL,
                                INICIO    TIMESTAMP WITH TIME ZONE NOT NULL,
                                FIM       TIMESTAMP WITH TIME ZONE NOT NULL,
                                CONSTRAINT PK_SESSAO PRIMARY KEY (ID),
                                CONSTRAINT FK_SESSAO_PAUTA FOREIGN KEY (PAUTA_ID) REFERENCES PAUTA(ID)
);

CREATE UNIQUE INDEX UQ_SESSAO_PAUTA ON SESSAO_VOTACAO (PAUTA_ID);
CREATE INDEX IDX_SESSAO_FIM ON SESSAO_VOTACAO (FIM);
