CREATE SEQUENCE SEQ_VOTO START WITH 1 INCREMENT BY 1;

CREATE TABLE VOTO (
                      ID           NUMBER(19) NOT NULL,
                      PAUTA_ID     NUMBER(19) NOT NULL,
                      CPF          VARCHAR2(11) NOT NULL,
                      VOTO         VARCHAR2(3) NOT NULL,
                      CREATED_AT   TIMESTAMP WITH TIME ZONE NOT NULL,
                      CONSTRAINT PK_VOTO PRIMARY KEY (ID),
                      CONSTRAINT FK_VOTO_PAUTA FOREIGN KEY (PAUTA_ID) REFERENCES PAUTA(ID),
                      CONSTRAINT UQ_VOTO_PAUTA_CPF UNIQUE (PAUTA_ID, CPF)
);

CREATE INDEX IDX_VOTO_PAUTA ON VOTO (PAUTA_ID);
CREATE INDEX IDX_VOTO_CREATED_AT ON VOTO (CREATED_AT);
