CREATE SEQUENCE SEQ_VOTO START WITH 1 INCREMENT BY 1;

CREATE TABLE VOTO (
                      ID           NUMBER(19) NOT NULL,
                      PAUTA_ID     NUMBER(19) NOT NULL,
                      ASSOCIADO_ID NUMBER(19) NOT NULL,
                      CPF          VARCHAR2(20) NOT NULL,
                      VOTO         VARCHAR2(10) NOT NULL,
                      CREATED_AT   TIMESTAMP WITH TIME ZONE NOT NULL,
                      CONSTRAINT PK_VOTO PRIMARY KEY (ID),
                      CONSTRAINT FK_VOTO_PAUTA FOREIGN KEY (PAUTA_ID) REFERENCES PAUTA(ID)
);

CREATE UNIQUE INDEX UQ_VOTO_PAUTA_ASSOCIADO ON VOTO (PAUTA_ID, ASSOCIADO_ID);
CREATE INDEX IDX_VOTO_PAUTA ON VOTO (PAUTA_ID);
